## initial list of manual builds in rpm-list-builder format (historical reasons)
## STEP 0: bump package version and set macros version to new python
#- python-rpm-macros
## build python3.N-1 together with python3.N without any bcond, verify python3.N-1 is nonmain python
#- python3.N:
#    macros:
#      _with_bootstrap: 1  # bump the release so it's greater even with ~bootstrap
#      _without_rpmwheels: 1
#      _without_tests: 1
#      _without_optimizations: 1
#- gdb: # not blocking (yet)
#    macros:
#      _without_python: 1
#- python-flit-core:
#    macros:
#      _with_bootstrap: 1  # bump the release so it's greater even with ~bootstrap
#- python-packaging:
#    macros:
#      _with_bootstrap: 1  # bump the release so it's greater even with ~bootstrap
#- python-setuptools:
#    macros:
#      _with_bootstrap: 1  # bump the release so it's greater even with ~bootstrap
#- python-wheel:
#    macros:
#      _with_bootstrap: 1  # bump the release so it's greater even with ~bootstrap
#- python-pip:
#    macros:
#      _without_tests: 1
#      _without_doc: 1
#- python-setuptools:
#    macros:
#      _without_tests: 1
#- pyparsing:  # python BuildRequires systemtap-sdt-devel Requires pyparsing
#    macros:
#      _without_tests: 1
#      _without_doc: 1
#      _without_extras: 1
## wait for gdb
#- python3.N
# VERIFY all of the above have correct Provides/Requires
# do a test/scratch build to VERIFY python3-rpm-generators work before proceeding!

[koji]
target = 'rawhide'
# target = 'f41-python'

[distgit]
branch = "rawhide"
commit_message = "Rebuilt for Python 3.13"
bootstrap_commit_message = "Bootstrap for Python 3.13"
author = "Python Maint <python-maint@redhat.com>"

[architectures]
repoquery = "x86_64" # used for repository querying
koji = "x86_64" # used to scratch build packages with bconds

[deps]
old = ["python(abi) = 3.12", "libpython3.12.so.1.0()(64bit)", "libpython3.12d.so.1.0()(64bit)"]
new = ["python(abi) = 3.13", "libpython3.13.so.1.0()(64bit)", "libpython3.13d.so.1.0()(64bit)"]

[components]
excluded = ["python3.12", "python3.13", "rust-add-determinism", "kernel"]
#extra = ["python3-docs"]
extra = []

[cache_dir]
dnf = "_dnf_cache_dir"
fedpkg = "_fedpkg_cache_dir"

[repos]
[[repos.rawhide]]
repoid = "rawhide"
# metalink = "https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch"
baseurl = ["https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20240610.n.0/compose/Everything/$basearch/os/"]
metadata_expire = 600000000

[[repos.rawhide]]
repoid = "rawhide-source"
# metalink = "https://mirrors.fedoraproject.org/metalink?repo=rawhide-source&arch=$basearch"
baseurl = ["https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20240610.n.0/compose/Everything/source/tree/"]
metadata_expire = 600000000

[[repos.target]]
repoid = "python3.13"
# baseurl = ["https://copr-be.cloud.fedoraproject.org/results/@python/python3.13/fedora-rawhide-$basearch/"]
baseurl = ["http://kojipkgs.fedoraproject.org/repos/f41-build/latest/$basearch/"]
metadata_expire = 60

[bconds]
[[bconds.python-setuptools]]
withs = ["bootstrap"]
withouts = ["tests"]

[[bconds.python-packaging]]
withs = ["bootstrap"]

[[bconds.python-wheel]]
withs = ["bootstrap"]

[[bconds.python-pip]]
withouts = ["tests", "doc"]

[[bconds.python-six]]
withouts = ["tests"]

[[bconds.python-tomli-w]]
withouts = ["check"]

[[bconds.python-setuptools_scm]]
withouts = ["tests"]

[[bconds.python-py]]
withouts = ["docs", "tests"]

[[bconds.python-chardet]]
withouts = ["doc"]

[[bconds.python-pbr]]
withs = ["bootstrap"]
withouts = ["tests"]

[[bconds.python-mock]]
withouts = ["tests"]

[[bconds.python-extras]]
withs = ["bootstrap"]

[[bconds.python-testtools]]
withs = ["bootstrap"]

[[bconds.python-attrs]]
withouts = ["tests"]

[[bconds.python-pluggy]]
withouts = ["tests"]

[[bconds.python-sortedcontainers]]
withouts = ["docs", "tests"]

[[bconds.python-hypothesis]]
withouts = ["doc", "tests"]

[[bconds.python-hypothesmith]]
withouts = ["tests"]

[[bconds.python-pygments]]
withouts = ["docs", "tests"]

[[bconds.python-filelock]]
withouts = ["docs", "tests"]

[[bconds.python-elementpath]]
withouts = ["tests"]

[[bconds.python-iniconfig]]
withouts = ["tests"]

[[bconds.Cython]]
withouts = ["tests"]

[[bconds.python-more-itertools]]
withouts = ["tests"]

[[bconds.python-atomicwrites]]
withouts = ["docs", "tests"]

[[bconds.python-fixtures]]
withs = ["bootstrap"]

[[bconds.python-wcwidth]]
withouts = ["tests"]

[[bconds.pytest]]
withouts = ["timeout", "tests", "docs"]

[[bconds.python-virtualenv]]
withs = ["bootstrap"]

[[bconds.babel]]
withs = ["bootstrap"]

[[bconds.python-jinja2]]
withouts = ["docs", "asyncio_tests"]

[[bconds.python-sphinx_rtd_theme]]
withs = ["bootstrap"]

[[bconds.python-sphinx-basic-ng]]
withs = ["bootstrap"]

[[bconds.python-urllib3]]
withouts = ["tests"]

[[bconds.python-requests]]
withouts = ["tests"]

[[bconds.python-sphinx]]
withouts = ["tests", "sphinxcontrib"]

[[bconds.python-jedi]]
withouts = ["tests"]

[[bconds.python-dateutil]]
withouts = ["tests"]

[[bconds.python-jsonschema]]
withouts = ["tests"]

[[bconds.python-sphinxcontrib-websupport]]
withouts = ["optional_tests"]

[[bconds.python-soupsieve]]
withouts = ["tests"]

[[bconds.python-pytest-asyncio]]
withouts = ["tests"]

[[bconds.python-pytest-cov]]
withouts = ["tests"]

[[bconds.python-flit-core]]
withouts = ["tests"]

[[bconds.python-async-timeout]]
withouts = ["tests"]

[[bconds.python-jupyter-client]]
withouts = ["doc","tests"]

[[bconds.python-jupyter-server]]
withouts = ["tests"]

[[bconds.python-matplotlib]]
withouts = ["check"]

[[bconds.ipython]]
withouts = ["check","doc"]

[[bconds.python-ipykernel]]
withouts = ["tests","doc"]

[[bconds.pybind11]]
withouts = ["tests"]

[[bconds.python-nbconvert]]
withouts = ["check", "doc"]

[[bconds.python-nbclient]]
withouts = ["check"]

[[bconds.python-pyquery]]
withouts = ["tests"]

[[bconds.python-cherrypy]]
withouts = ["tests"]

[[bconds.freeipa-healthcheck]]
withouts = ["tests"]

[[bconds.python-zbase32]]
withs = ["bootstrap"]

[[bconds.python-Traits]]
withs = ["bootstrap"]

[[bconds.python-lit]]
withouts = ["check"]

[[bconds.python-pcodedmp]]
withs = ["bootstrap"]

[[bconds.python-libcst]]
withouts = ["tests", "docs"]

[[bconds.python-databases]]
withs = ["bootstrap"]

[[bconds.scipy]]
withouts = ["pythran"]

[[bconds.python-pandas]]
withs = ["bootstrap"]

[[bconds.python-fasteners]]
withouts = ["tests"]

[[bconds.python-zope-event]]
withs = ["bootstrap"]
withouts = ["docs"]

[[bconds.python-zope-interface]]
withouts = ["tests", "docs"]

[[bconds.python-tqdm]]
withouts = ["tests"]

[[bconds.python-cryptography]]
withouts = ["tests"]

[[bconds.python-decopatch]]
withouts = ["tests"]

[[bconds.python-geopandas]]
withs = ["bootstrap"]

[[bconds.python-astropy]]
withouts = ["check"]

[[bconds.python-pyerfa]]
withouts = ["tests"]

[[bconds.python-aiohttp]]
withouts = ["tests"]

[[bconds.python-azure-core]]
withouts = ["tests"]

# this bcond is disabled in spec on purpose
# it might be enabled in the future, so leaving this here, commend out
#[[bconds.python-azure-common]]
#withouts = ["tests"]

[[bconds.python-azure-mgmt-core]]
withouts = ["tests"]

[[bconds.python-subprocess-tee]]
withouts = ["tests"]

[[bconds.python-typeguard]]
withs = ["bootstrap"]

[[bconds.python-tox]]
withs = ["bootstrap"]

[[bconds.python-pytest-rerunfailures]]
withouts = ["tests"]

[[bconds.python-fsspec]]
withs = ["bootstrap"]

[[bconds.python-pyface]]
withs = ["bootstrap"]

[[bconds.python-contourpy]]
withs = ["bootstrap"]

[[bconds.python-msrest]]
withouts = ["tests"]

[[bconds.python-oletools]]
withs = ["bootstrap"]

[[bconds.python-google-api-core]]
withouts = ["tests"]

[[bconds.fonttools]]
withouts = ["tests"]

[[bconds.conda]]
withouts = ["tests"]

[[bconds.conda-build]]
withouts = ["tests"]

[[bconds.python-conda-libmamba-solver]]
withouts = ["tests"]

[[bconds.python-conda-index]]
withs = ["bootstrap"]

[[bconds.python-conda-package-streaming]]
withs = ["bootstrap"]

[[bconds.python-googleapis-common-protos]]
withs = ["bootstrap"]

[[bconds.python-proto-plus]]
withouts = ["tests"]

[[bconds.python-dns]]
withouts = ["trio", "curio", "doh"]

[[bconds.python-poetry-plugin-export]]
withs = ["bootstrap"]

[[bconds.poetry]]
withs = ["bootstrap"]

[[bconds.python-networkx]]
withs = ["bootstrap"]

[[bconds.python-beautifulsoup4]]
withouts = ["soupsieve", "tests"]

[[bconds.python-lxml]]
withouts = ["extras"]

[[bconds.python-constantly]]
withouts = ["tests"]

# this is intentionally commented out
# 1) is is part of the initial bootstrap
# 2) replacement does not work, the macro isn't there (needs to be added)
#[[bconds.gdb]]
#replacements = {_without_python = "1"}

[[bconds.python-pysocks]]
replacements = {with_python3_tests = "0"}

[[bconds.ara]]
replacements = {with_docs = "0"}

[[bconds.python-httpretty]]
replacements = {run_tests = "0"}

[[bconds.python-ruamel-yaml]]
withs = ["bootstrap"]

[[bconds.python-rq]]
withouts = ["tests"]

[[bconds.python-markdown-it-py]]
withouts = ["plugins"]

[[bconds.python-factory-boy]]
withouts = ["tests"]

[[bconds.python-tox-current-env]]
withs = ["bootstrap"]

[[bconds.python-pikepdf]]
withouts = ["docs", "tests"]

[[bconds.python-executing]]
withouts = ["tests"]

[[bconds.python-editables]]
withouts = ["doc"]

[[bconds.python-jsonschema-specifications]]
replacements = {with_doc = "0"}

[[bconds.python-openstackclient]]
replacements = {with_doc = "0"}

[[bconds.python-oslo-config]]
replacements = {repo_bootstrap = "1"}

[[bconds.python-neutronclient]]
replacements = {with_doc = "0"}

[[bconds.python-glanceclient]]
replacements = {with_doc = "0"}

[[bconds.python-domdf-python-tools]]
withouts = ["tests"]

[[bconds.python-tiny-proxy]]
withouts = ["tests"]

[[bconds.python-werkzeug]]
withouts = ["tests"]

[[bconds.python-netaddr]]
withouts = ["docs"]

[[bconds.python-dirty-equals]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-storage-plugins]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-executor-plugins]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-report-plugins]]
withs = ["bootstrap"]

[[bconds.snakemake]]
withs = ["bootstrap"]

[[bconds.python-sphinx-theme-builder]]
withs = ["bootstrap"]

[[bconds.python-httpx]]
withouts = ["tests"]

[[bconds.python-oslo-i18n]]
replacements = {with_doc = "0"}

[[bconds.python-pymssql]]
withouts = ["tests"]

[[bconds.python-zmq]]
withouts = ["gevent"]

[[bconds.python-django]]
withouts = ["tests"]

[[bconds.python-authlib]]
withouts = ["tests"]

[[bconds.python-oslotest]]
withs = ["repo_bootstrap"]

[[bconds.python-gunicorn]]
withouts = ["extras"]

[[bconds.python-execnet]]
withouts = ["optional_test_deps"]

[[bconds.python-threadpoolctl]]
withouts = ["check"]

[[bconds.python-tabulate]]
withs = ["bootstrap"]

[[bconds.python-repoze-sphinx-autointerface]]
withouts = ["tests"]

[[bconds.python-zope-exceptions]]
withouts = ["tests"]

[[bconds.python-deepdiff]]
withouts = ["tests"]

[[bconds.python-sentry-sdk]]
withouts = ["tests"]

# [[bconds.OpenColorIO]]
# %global bootstrap 1
# we lack config syntax for that :(
